[project]
authors = ["Joseph Kuo <jovesus@gmail.com>"]
channels = ["conda-forge"]
name = "scHTO"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pyyaml = ">=6.0.2,<7"
pytest = ">=8.3.4,<9"
setuptools = ">=75.8.0,<76"
pip = ">=25.0.1,<26"
