# Sample configuration for cshto

libraries_with_HTOs:
  - htolib_name: pool1
    R12: R1
    path: fastq/pool1_hto_R1.fastq.gz
  - htolib_name: pool1
    R12: R2
    path: fastq/pool1_hto_R2.fastq.gz

positions:
  - name: cell_barcode_start
    position: 1
    R12: R1
  - name: cell_barcode_end
    position: 16
    R12: R1
  - name: umi_start
    position: 17
    R12: R1
  - name: umi_end
    position: 26
    R12: R1
  - name: hto_start
    position: 1
    R12: R2
  - name: hto_end
    position: 11
    R12: R2

libraries_to_be_demultiplexed:
  - htolib_name: pool1
    R12: R1
    path: fastq/pool1_GEX_R1.fastq.gz
  - htolib_name: pool1
    R12: R2
    path: fastq/pool1_GEX_R2.fastq.gz

HTO_sequences:
  - htolib_name: pool1
    sample_name: sample1
    hto_sequence: AGCTGGTCGAACG
  - htolib_name: pool1
    sample_name: sample2
    hto_sequence: AGCTCCTCGAACG

cutoffs:
  min_umi: 5

expected_cell_number:
  - htolib_name: pool1
    sample_name: sample1
    estimate_number: 30000
  - htolib_name: pool1
    sample_name: sample2
    estimate_number: 30000