# Sample configuration for cshto

libraries_with_HTOs:
  - htolib_name: pool1
    R12: R1
    # path: /Users/ckuo/Downloads/Pool1_cell_surface_protein_Merged_R1_001.fastq.gz
    path: /Users/ckuo/Downloads/Pool1_cell_surface_protein_sample_R1.fastq.gz
  - htolib_name: pool1
    R12: R2
    # path: /Users/ckuo/Downloads/Pool1_cell_surface_protein_Merged_R2_001.fastq.gz
    path: /Users/ckuo/Downloads/Pool1_cell_surface_protein_sample_R2.fastq.gz

positions:
  cell_barcode_R12: R1
  cell_barcode_start: 1
  cell_barcode_end: 16
  umi_R12: R1
  umi_start: 17
  umi_end: 28
  hto_R12: R2
  hto_start: 1
  hto_end: 15

libraries_to_be_demultiplexed:
  - htolib_name: pool1
    R12: R1
    path: /Users/ckuo/Downloads/Pool1_GEX_sample_R1.fastq.gz
  - htolib_name: pool1
    R12: R2
    path: /Users/ckuo/Downloads/Pool1_GEX_sample_R2.fastq.gz

HTO_sequences:
  - htolib_name: pool1
    sample_name: sample1
    hto_sequence: TTGGCCTTTGTATCG
  - htolib_name: pool1
    sample_name: sample2
    hto_sequence: AACGCCAGTATGAAC
  - htolib_name: pool1
    sample_name: sample3
    hto_sequence: GCTTCCGTATATCTG

expected_cell_number:
  - htolib_name: pool1
    sample_name: sample1
    estimate_number: 30000
  - htolib_name: pool1
    sample_name: sample2
    estimate_number: 30000
  - htolib_name: pool1
    sample_name: sample3
    estimate_number: 30000